--- #YAML:1.0
name:                Module-Extract-Use
version:             0.12
abstract:            Extract the modules that a modules uses
license:             perl
author:              
    - brian d foy <bdfoy@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    PPI:                           0
    Test::More:                    0
    Test::Output:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
